changeTargetInterval: 600
riseCoef: 0.0625
centrifugalCoef: 0.0625
metadataKey: TornadoPluginEntity
exceptCreatives: true
exceptSpectators: true
exceptFlowing: true
limitInvolvedEntity: 0
involveBlockProbability: 1.0
involveEntityProbability: 1.0