name: TornadoPlugin
version: ${project.version}
main: net.kunmc.lab.tornadoplugin.TornadoPlugin
api-version: 1.16
commands:
  tornado:
    usage: |-
      /tornado summon entity <selector> <tornadoName> <radius> <height> <speed>
      /tornado summon location <world> <x> <y> <z> <tornadoName> <radius> <height> <speed>
      /tornado remove <tornadoName>
      /tornado modify <tornadoName> <settingItem> <value>
