name: TornadoPlugin
version: ${project.version}
main: net.kunmc.lab.tornadoplugin.TornadoPlugin
api-version: 1.16
commands:
  tornado:
    usage: |-
      /tornado summon <name> <selector> <radius> <height> <speed>
      /tornado remove <name>
      /tornado modify <name> <settingItem> <value>
